### ISSUE TITLE
Paint over DOS keys ("F1", "F2", "F3") in main menu

### ISSUE THREAD

**Issue by therourke** [esoteric-programmer/lemmings_3ds#14]
The main menu with the 4 lemmings holding placards is too small. Is it possible to enlarge the 3 lemmings which hold options, or at least make their keys bigger?

**Comment by esoteric-programmer** [comment]
You need not touch at the key. You can touch anywhere at the lemming. So I guess, they are large enough?
To change difficulty, you can touch anywhere at the top (increase) or at the bottom (decrease) of the lemming.

Btw., the graphics are from DOS Lemmings, so the keys displayed there (F1, F2, F3) don't make any sense for 3DS. Maybe I could overdraw them to avoid confusion...
