### ISSUE TITLE
Add Static Downloads for the zip, cia, and 3dsx files

### ISSUE THREAD

**Issue by Cralex** [esoteric-programmer/lemmings_3ds#15]
Adding these will not only make it easier for end users to find the game, but (specifically the cia file) will enable the game to be indexed by www.titledb.com and, by extension, the Homebr3w app (https://github.com/Wolvan/Homebr3w/blob/master/README.md)

This would make it easy for users of the cia version to recieve updates right from their 3ds. If it doesn't already exist, I'd also add an error message with the URL of the zip file if someone launches the game without any levels installed. That way, people who install the game without the needed files will know what to do.

**Comment by esoteric-programmer** [comment]
What do you mean with "static" Downloads?How should it differ from the current [Release](https://github.com/esoteric-programmer/lemmings_3ds/releases)? Do you mean a link that doesn't change for a new version? If yes, how could I do this with github?

Btw., latest commit adds some error messages.

**Comment by Cralex** [comment]
Sorry, I'm new at github, so I thought the only download link was on gbatemp. Didn't realize there was a releases page because I couldn't find a link to it.

I also wasn't  aware that www.titledb.com is able to handle compressed archives, without needing a direct link to a CIA file. Whenever I tried adding the lemmings archive, it produced an error, but it turns out that was an error on their end. Lemmings now appears on the site and any updates on the github releases page should be automatically tracked. Thanks anyway.
