### ISSUE TITLE
Change volume of music / sfx

### ISSUE THREAD

**Issue by therourke** [esoteric-programmer/lemmings_3ds#23]
I tend to turn the music off so I can concentrate on sfx, but this choice does not get saved upon loading the game again.

Also, the music tends to drown out the sfx, which can be a pain. Any way to foregrounded sfx a little over the background music? Perhaps even add separate volume options for each.

**Comment by esoteric-programmer** [comment]
The status will be saved now. However, I keep this issue open until volume options are implemented.
