### ISSUE TITLE
Resources directory's path

### ISSUE THREAD

**Issue by Rick-74** [esoteric-programmer/lemmings_3ds#47]
It would really be great if the users could be able to change the resources directory's path to an existing subdirectory, to unclutter the SD card's root: something like e.g. /3ds/lemmings (as it seems that other homebrews already chose /3ds/ as their config's directory).

**Comment by esoteric-programmer** [comment]
The feature has been added with commit bfff7f601365f3e6c23d068c6cfca85e2daae609:
If /lemmings does not exist, the game uses /3ds/lemmings instead.
